[package]
name = "braille-images"
version = "0.2.0"
edition = "2024"

[dependencies]
image = "0.25"
palette = "0.7"
clap = { version = "4.5", features = ["derive"] }
terminal_size = "0.4"

[profile.release]
strip = true
debug = false
panic = "abort"
lto = "fat"
